export const actionTypes = {
  VIEW_SPECIFIC_CATEGORY: 'VIEW_SPECIFIC_CATEGORY',
  VIEW_ALL_CATEGORIES: 'VIEW_ALL_CATEGORIES',
  VIEW_NEXT_PAGE: 'VIEW_NEXT_PAGE',
  VIEW_PREV_PAGE: 'VIEW_PREV_PAGE',
  VIEW_CLOTHING_DETAILS: 'VIEW_CLOTHING_DETAILS',
  FETCHED_ALL_CATEGORIES: 'FETCHED_ALL_CATEGORIES',
  FETCHING_CATEGORIES: 'FETCHING_CATEGORIES',
  ERROR_FETCHING_CATEGORIES: 'ERROR_FETCHING_CATEGORIES',
};
