export const actionTypes = {
  VIEW_NEXT_PAGE: 'VIEW_NEXT_PAGE',
  VIEW_PREV_PAGE: 'VIEW_PREV_PAGE',
  FETCHED_ALL_CATEGORIES: 'FETCHED_ALL_CATEGORIES',
  FETCHING_CATEGORIES: 'FETCHING_CATEGORIES',
  ERROR_FETCHING_CATEGORIES: 'ERROR_FETCHING_CATEGORIES',
  FETCHING_POSTS: 'FETCHING_POSTS',
  ERROR_FETCHING_POSTS: 'ERROR_FETCHING_POSTS',
  FINISH_FETCHING_POSTS: 'FINISH_FETCHING_POSTS', 
};
