export const actionTypes = {
  FETCHED_ALL_CATEGORIES: 'FETCHED_ALL_CATEGORIES',
  FETCHING_CATEGORIES: 'FETCHING_CATEGORIES',
  ERROR_FETCHING_CATEGORIES: 'ERROR_FETCHING_CATEGORIES',
  FETCHING_POSTS: 'FETCHING_POSTS',
  ERROR_FETCHING_POSTS: 'ERROR_FETCHING_POSTS',
  FINISH_FETCHING_POSTS: 'FINISH_FETCHING_POSTS',
  ACTIVE_CATEGORY_CHANGED: 'ACTIVE_CATEGORY_CHANGED',
  FINISH_FETCHING_CONSEQUENT: 'FINISH_FETCHING_CONSEQUENT',
};
